### ISSUE TITLE
Boolean features show up as errors

### ISSUE THREAD

**Issue by ek-nath** [PAIR-code/facets#12]
I have boolean features which are either 0.0 / 1.0 (`numpy.float`s). Because they're zero (legitimately), facets considers them to be erroneous. Is there a different datatype I should be using for booleans?

**Comment by jameswex** [comment]
If the issue is that the "zeros" entry for that boolean column is showing up as bolded and red, then that is a result of overview treating all numeric features in the same way. There currently is no way to turn off that behavior for numeric types, but it should be having no effect other than visually displaying that field as bold and red.

If you change the datatype of that column to something non-numeric (like casting those to strings "0" and "1" or "true" and "false") then that feature will show up in the "categorical" table instead, and give a bar chart of the number of trues and false entries as opposed to a histogram. Visually, this probably makes more sense for your boolean feature in terms of visualizing the contents.

**Comment by ek-nath** [comment]
Good point. Thanks
