### ISSUE TITLE
HTML Imports is deprecated error still here!

### ISSUE THREAD

**Issue by markddesimone** [PAIR-code/facets#228]
![image](https://user-images.githubusercontent.com/5612966/95524871-68e4eb80-0987-11eb-8b34-eaaabaef17d3.png)

I was getting this error so I checked the sample: https://colab.research.google.com/github/PAIR-code/facets/blob/master/colab_facets.ipynb. it is still getting the error.

I am on linux Ubuntu 18.04.5 LTS, Chrome Version 85.0.4183.121 (Official Build) (64-bit)

The script is using:
<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.3.3/webcomponents-lite.js"></script>

as recommended as the solution in https://github.com/PAIR-code/facets/issues/206 and https://github.com/PAIR-code/facets/issues/211

**Comment by jameswex** [comment]
Thanks for reaching out. That warning in the console is now expected, as Facets uses HTML imports, but through the webcomponents polyfill script, which is necessary since native suppoort was removed in Chrome M80.

Assuming the Facets visualizations are working as expected, the warning should be ignored.

**Comment by markddesimone** [comment]
@jameswex, thank you.  It works when the cell is first executed but if I re-run the cell I have the issues described in https://github.com/PAIR-code/facets/issues/227. I had been wondering if this was the cause. I have to totally restart jupyter to get the cell to render properly again, just shutting down the kernel for the notebook does not resolve it...

**Comment by mugglmenzel** [comment]
The issue still is present in Jupyter notebooks. Facets is not usable anymore on any Google Cloud notebook (CAIP, Vertex AI).

**Comment by jameswex** [comment]
@mugglmenzel As a test I just created a new virtualenv, did "pip install jupyter facets-overview protobuf", then ran "jupyter notebook" and ran the "Facets Dive and Overview Colab Example" notebook (skipping the first cell as that is only for when running in colab). I was able to see the Facets visualization, even though the HTML imports warning is shown (as expected).

Are you able to use it in plain Jupyter notebooks? I'm wondering if the issue is with a specific notebook environment and not all jupyter notebooks.
