### ISSUE TITLE
Trying to find the use cases for google facets

### ISSUE THREAD

**Issue by infinite-Joy** [PAIR-code/facets#42]
Hi Team, great work with the both overview and dive. I have been looking at the things that this application is able to do and would appreciate it if you can share the motivations for creating this repo. I am thinking of using this application for my current datascience project and would like to understand your motivations so that I can think of cool insights that I can draw from my datasets.

**Comment by jameswex** [comment]
Best summing up the motivation would be the motto: "Debug your data".

In building ML models, we found a lot of missteps and failed models were due to people not truly understanding the distributions and relationships in their data. So we built these tools to quickly and easily get broad understanding of datasets, mainly for the use case of understanding training data for ML models, but it could be applied to any datasets really.

**Comment by jameswex** [comment]
Closing this issue, please reopen if necessary.
