### ISSUE TITLE
I want to know how can i use the facets overview and dive to visualize my data?

### ISSUE THREAD

**Issue by programmeDuan** [PAIR-code/facets#61]

**Comment by jameswex** [comment]
What format is your data in? If the data is small, the simplest approach is uploading it as a csv to the demo page for facets at https://pair-code.github.io/facets/ 

For larger data, you probably want to do it in a jupyter notebook and follow the example jupyter notebooks (one in the facets_overview directory and one in the facets_dive directory) but load in your own data into a pandas DataFrame instead of the UCI census data used in the example notebooks.

**Comment by jameswex** [comment]
Closing this issue, please reopen if necessary.
