### ISSUE TITLE
How to see large datasets in dive similar to the one in overview

### ISSUE THREAD

**Issue by infinite-Joy** [PAIR-code/facets#62]
In the [overview example][1], it is shown how to render a large dataset using google protocol buffers. There `protostr` was passed to `document.querySelector("#elem").protoInput` in cell 4. How can we implement the same thing in dive? In the [dive example][2] a record based json string is used with a much smaller dataset. I am trying to test dive using a dataset of larger size.

[1]: https://github.com/PAIR-code/facets/blob/master/facets_overview/Overview_demo.ipynb
[2]: https://github.com/PAIR-code/facets/blob/master/facets_dive/Dive_demo.ipynb

**Comment by jameswex** [comment]
Whereas overview takes a proto containing the dataset's feature statistics, dive takes records in json format. How large of a dataset are you planning on trying in number of records and features/columns per records? Dive, since it visualizes all data of all records provided to it in the browser, cannot handle huge datasets  - you would need to sample from the dataset and show a subset of data. We often use dive with tens of thousands of records, but not hundreds of thousands. And each record has a handful of features. The more features per record, the smaller number of records that could be handled before browser memory issues.

**Comment by jameswex** [comment]
Closing this issue. Please reopen if necessary.
