### ISSUE TITLE
tried using in webpage but failed.

### ISSUE THREAD

**Issue by gerard0315** [PAIR-code/facets#78]
I was trying to start the service only on webpage rather than in a notebook, using `bazel run facets:facets`  the webpage on `http://127.0.0.1:6006/facets/visualizations.html` did not render and gave me several JS syntex import errors like `import CommonStatistics from 'goog:proto.featureStatistics.CommonStatistics';`. It it even possible to start the service this way?

**Comment by jameswex** [comment]
You can build facets.html with bazel build facets:facets, and then use this facets.html in your own webserver in order to embed facets into a webpage, but I you can't use bazel run facets:facets to start a webserver that will allow you to interactively use facets out of the box.

See how facets.html is used on the gh-pages branch to see how it can be done (which is what is served at https://pair-code.github.io/facets/): https://github.com/PAIR-code/facets/tree/gh-pages
