### ISSUE TITLE
ImportError: No module named 'generic_feature_statistics_generator'

### ISSUE THREAD

**Issue by stravinsky7** [PAIR-code/facets#83]
Self taught,- this may be really obvious.  However I've been stuck for a day so..

https://github.com/PAIR-code/facets/blob/master/facets_dive/Dive_demo.ipynb

works just fine.  However, once I get to the import at 

https://github.com/PAIR-code/facets/blob/master/facets_overview/Overview_demo.ipynb

everything breaks down.  I am running it from jupyter in an Anaconda environment.  Does something need to be done to enable this import?

edit: While I'm here, thank you, what a neat extension.  :)

**Comment by jameswex** [comment]
It's probably the case that the python environment you are running in does now see the generic_Feature_statistics_generator python module included with this project.

In that demo notebook you see in the top cell that we do:
  import sys  
  sys.path.append('./python')

We do that because the jupyter environment was started from the facets_overview directory (which contains the demo ipython notebook). There is a subdirectory "python" there that contains the  generic_feature_statistics_generator module. That sys.path.append is telling the python interpreter to look in that directory for modules we try to import.

You will need to do something similar, correctly pointing at the path where that module exists.

Let me know if that helps.

**Comment by secsilm** [comment]
@jameswex yes it works, but after restarting kernel.

**Comment by contractorwolf** [comment]
solved it for me, thanks. Restarted the kernel as well.
